### ISSUE TITLE
Group Viewer broken on Brave?

### ISSUE THREAD

**Issue by HEROshineMC** [NabokD/pockettube#10]
The group viewer has options to view 50, 100, 200, or 500 videos, but every option after 50 just shows 60 videos (the groups I tested with easily have thousands of videos, so it's not that there are just 60 videos to show, it is actually broken). The playlist button also only generates 60 videos, as opposed to 100, 200, or 500. Also since infini-scroll is a paid feature, are there supposed to be pagination buttons? Because those don't show up on Brave either, if they're supposed to :<

Well thanks for reading, I hope I brought some issues to your attention. This extension is amazing, and I would love to see it fully work on Brave :)

Edit: Okay so I tested other channel groups and they load different amounts than 60.. One was 66 and one was 30. Also it actually doesn't seem to be Brave incompatibility, as the same issue is on Chrome as well.

Edit 2: Drive backup/sync doesn't seem to work. I'm signed into the extension on both Brave and Chrome, and have sync enabled but my channel groups on Brave aren't syncing onto Chrome.

I hope none of this comes across as me being nit picky or rude 😅 Your extension is great, I just really wish it would work for me haha

**Comment by NabokD** [comment]
Hi

The extension has a youtube restriction I can get 15 latest videos per channel. For this reason, in your case, you have ~4 channels in the group and watch the latest 60 videos. The extension doesn't have page pagination buttons.

In my case, sync works. Are you using the latest version of both browsers/extensions? The latest extension version is 9.10.12. Did you use the same Google account in both browsers? What did you see after clicking on enable button and sign in? You have to see 'Data has been synced'.

**Comment by HEROproductions** [comment]
> The extension has a youtube restriction I can get 15 latest videos per channel. For this reason, in your case, you have ~4 channels in the group and watch the latest 60 videos. The extension doesn't have page pagination buttons.

Ohh I see. Is that a limit with YouTube's API? (I've never worked with their API so this is above my metaphorical pay grade haha). If so that's really a shame :( The biggest thing that drew me to this extension was being able to see basically a normal video page for a channel but for several channels, so only seeing 15 mainly works great if it's a group of channels I'm not far behind on, but if it is a limit with YouTube's API then I understand there's not much you could do about that,

> In my case, sync works. Are you using the latest version of both browsers/extensions? The latest extension version is 9.10.12. Did you use the same Google account in both browsers? What did you see after clicking on enable button and sign in? You have to see 'Data has been synced'.

Hmm well I logged out of both to double-check I was using the same account (both browsers & extensions are also up-to-date), and now when clicking "enable sync" on the extension for Chrome it just does the spinning load animation forever :< (I also tried uninstalling the extension and reopening Chrome). Although I mainly just use Brave so it doesn't really affect me, but if there's a log file or something I can send to help you find the issue I can do that 👍

**Comment by Tiltowait2** [comment]
I'm using Brave and...I don't see anything.  I can't get to the window shown in the video.  All I get is a screen saying Settings | Notifications | Backup.  How do I actually add videos to a playlist?

**Comment by NabokD** [comment]
> I'm using Brave and...I don't see anything. I can't get to the window shown in the video. All I get is a screen saying Settings | Notifications | Backup. How do I actually add videos to a playlist?

What do you mean? What videos to a playlist? Watch tutorial video: https://www.youtube.com/watch?v=rylGj42u034

**Comment by Tiltowait2** [comment]
OK that's better, I guess (it wasn't in the most recent video) but that screen only lets you add complete channels?  I want to put any video on youtube into a list.

**Comment by NabokD** [comment]
Yes, PocketTube supports channels and playlists. I don't have about videos.
