### ISSUE TITLE
Play all only plays 1 video

### ISSUE THREAD

**Issue by RomeoAlphaEkko** [NabokD/pockettube#101]
if you see like 4 or 5 videos and click the play all button, it only plays one video, even if it runs to the end it stops, there is no playlist hidden, appeared like a couple of days ago, sometimes it works but most times it does not

**Comment by NabokD** [comment]
Hi, thank you for letting me know. It seems like YouTube's unlisted playlist is working unstable, I'm going to add a workaround to fix the issue on YouTube.

Currently, you can change the video count to 100 or more on the feed, and after that, the playlist will be using private type instead of unlisted.

**Comment by NabokD** [comment]
The new version 16.1.5 is available with a workaround to create private playlist when youtube can't create  unlisted
