### ISSUE TITLE
Thumbnails of normal videos and shorts have different heights at home page?

### ISSUE THREAD

**Issue by hmpthz** [NabokD/pockettube#106]
![Screenshot 2024-06-29 013648](https://github.com/NabokD/pockettube/assets/44091340/27840894-e1ae-4cd9-b8e4-f1902a118030)
This issue only exists at home page, when you click the group tab to see all videos, their thumbnails are fine.
I've tried to debug by throttling network, it appears that at first the short shows a picture with correct size, just like the group page:
https://i3.ytimg.com/vi/2Iv5JLlUJlc/mqdefault.jpg
Then it is quickly replaced with another bigger picture,
https://i.ytimg.com/vi/2Iv5JLlUJlc/oar2.jpg?sqp=-oaymwEdCJUDENAFSFWQAgHyq4qpAwwIARUAAIhCcAHAAQY=&rs=AOn4CLCuY-HX3ZGwb9fQ6nOv0bkhw8w2xg
Any ideas?

**Comment by NabokD** [comment]
What extension version are you using?
Yes, we improved the quality of the thumbnails a week ago and discovered the improvement thumbnails had different heights for shorts. It was fixed in the latest version 16.1.8 which was released yesterday, the version is already available on Chrome and Safari. It'll be available for other browsers after review on the browser web stores.

**Comment by hmpthz** [comment]
> What extension version are you using? Yes, we improved the quality of the thumbnails a week ago and discovered the improvement thumbnails had different heights for shorts. It was fixed in the latest version 16.1.8 which was released yesterday, the version is already available on Chrome and Safari. It'll be available for other browsers after review on the browser web stores.

Thanks for the reply, I'm using edge which 16.1.7 is the latest. I will try the new release as soon as it is updated!

**Comment by NabokD** [comment]
The new version is available for Edge
