### ISSUE TITLE
tracking

### ISSUE THREAD

**Issue by urfausto** [NabokD/pockettube#12]
why do yousub extensions need to track user activity? i don't see the point in it...
this is raising much privacy concern to me.

**Comment by NabokD** [comment]
Check our Privacy Policy: https://yousub.info/privacy.html
---
This extension uses Mixpanel, a web analytics service provided by Mixpanel, Inc. (“Mixpanel”). Mixpanel uses “cookies”, which are text files placed on your computer, to help the website analyze how users use the site.

To improve the content, features and overall experience of the extension, we gather and log data on how our users access and use PocketTube. For example, we may log actions like clicking on collection name, open tv mode, change image or set settings.

Some of this usage data is sent to Mixplanel. In these cases, we do not send any identifying information that could be correlated with your account. We also make use of their IP anonymization feature to prevent your IP from being associated with your usage data.
---
All data sent to analytics is anonymized. So I can see only the summary number about using my extension. It helps me improve my features and the overall user experience of the extension.
You can use the Firefox version, it is tracking-free because their store doesn't allow it.

**Comment by urfausto** [comment]
ok but this slows down my browsing nonetheless, and i already have a much old hardware at the moment...

not that useful for you, more of a pain for me...

**Comment by NabokD** [comment]
There is no pain. I collect pieces of information that will be useful for improving extension. I'm not collecting your YouTube information like scrolling, watching videos id, etc. It does not slow down browsing nonetheless.

**Comment by urfausto** [comment]
that's weird because i'm seeing an incredible anomalous usage from one of the extensions:

![Senza nome](https://user-images.githubusercontent.com/31393590/143765026-2d5fd41f-549d-49c3-b791-a75292b9adbf.png)

**Comment by urfausto** [comment]
now it is working much better...

![Senza nome](https://user-images.githubusercontent.com/31393590/143774242-b85608df-1d40-451f-a779-dc8dd1df611e.png)

**Comment by NabokD** [comment]
I didn't change anything recently.
